### ISSUE TITLE
--preprocess fails with missing MNI template

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#9]
I've installed TractSeg by doing

```
pip install https://github.com/MIC-DKFZ/TractSeg/archive/v1.5.zip
```

When I run TractSeg with --preprocess option, it fails with following error message.

```
Moving input to MNI space...
Image Exception : #22 :: ERROR: Could not open image /usr/local/lib/python2.7/dist-packages/tractseg/libs/../../examples/resources/MNI_FA_template
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
Image Exception : #22 :: ERROR: Could not open image /usr/local/lib/python2.7/dist-packages/tractseg/libs/../../examples/resources/MNI_FA_template
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
```

Is something wrong with the way TractSeg wheel is installed? I don't see "examples" directory under dist-packages directory.

```
hayashis@gpu1-pestillilab:/usr/local/lib/python2.7/dist-packages 2 ls -la examples
ls: cannot access 'examples': No such file or directory
hayashis@gpu1-pestillilab:/usr/local/lib/python2.7/dist-packages 2 ls -la tractseg/
total 48
drwxr-sr-x  6 hayashis hayashis 4096 Sep 26 16:00 .
drwxrwsr-x 74 hayashis hayashis 4096 Sep 26 17:10 ..
-rw-r--r--  1 hayashis hayashis 9516 Sep 26 16:00 TractSeg.py
-rw-r--r--  1 hayashis hayashis 6010 Sep 26 16:00 TractSeg.pyc
-rw-r--r--  1 hayashis hayashis    0 Sep 26 16:00 __init__.py
-rw-r--r--  1 hayashis hayashis  146 Sep 26 16:00 __init__.pyc
drwxr-sr-x  4 hayashis hayashis 4096 Sep 26 16:00 config
drwxr-sr-x  2 hayashis hayashis 4096 Sep 26 16:00 libs
drwxr-sr-x  4 hayashis hayashis 4096 Sep 26 16:00 models
drwxr-sr-x  2 hayashis hayashis 4096 Sep 26 16:00 tests
```

**Comment by soichih** [comment]
By the way, I've manually copied the examples directory to my dist-packages directory, but it's still failing - looks like flirt crashing somehow?

```
Creating brain mask...
Moving input to MNI space...
terminate called after throwing an instance of 'NEWMAT::SingularException'
Creating brain mask...

Error: input image ./tractseg_output/Diffusion_MNI not valid
```

**Comment by wasserth** [comment]
Good point! Thanks for finding that bug. I pushed a fix to the master branch. I hope it works now. Could you check it again?

**Comment by soichih** [comment]
@wasserth Thanks. I've installed is using master and preprocess seems to starts successfully now.

However, I am still seeing this error message (from flirt)

```
Creating brain mask...
Moving input to MNI space...
terminate called after throwing an instance of 'NEWMAT::SingularException'
Creating brain mask...

Error: input image ./tractseg_output/Diffusion_MNI not valid
```

I am just using fsl that comes with Ubuntu 16.04 (apt-get install fsl). Maybe it's not the right version of fsl?

**Comment by wasserth** [comment]
I am using FLIRT version 6.0. I installed it using the installer and not the apt package. That might be the reason.

**Comment by soichih** [comment]
Ah, I wasn't aware that Ubuntu 16 distributes FSL 5.. I've switched it to use neurodebian:stretch-non-free and now it's installing FSL 6.

TractSeg now works with --preprocess option! Thanks!!
